### ISSUE TITLE
How to compile for ARM

### ISSUE THREAD

**Issue by AbuBaniaz** [LraiZer/RadiotimesXmltvEmulator#2]
LraiZer, how do we compile this for Arm receivers please? Including 64 bit like osmio 4k.

**Comment by AbuBaniaz** [comment]
Found it here
```
http://www.ukcvs.net/forum/showthread.php?30581-RadioTimes-XMLTV-Emulator&p=58450&viewfull=1#post58450
```

**Comment by AbuBaniaz** [comment]
Have an issue, will continue on forum

**Comment by LraiZer** [comment]
Seems there is an issue with DVB polling on some boxes, as I get no issues with poll disabled.

 NO_DVB_POLL patch has been applied in this [commit](https://github.com/LraiZer/RadiotimesXmltvEmulator/commit/664fb454f173b7510628e6f822e8da7bcb22c5ec)
