### ISSUE TITLE
Channel names are not grabbed anymore

### ISSUE THREAD

**Issue by doglover3920** [LraiZer/RadiotimesXmltvEmulator#7]
The channel names are not grabbed anymore.

Example;
[skyit_13.0.channels.zip](https://github.com/LraiZer/RadiotimesXmltvEmulator/files/7834651/skyit_13.0.channels.zip)

**Comment by LraiZer** [comment]
I only have 28.2e at the moment, I will try to get my rotor dish working again and re-aligned to inspect the signal data we are reading for the channel names on 13e. This may only be a possible in couple of weeks time though.

I've grabbed 28.2e and the channel names are grabbed ok there. 

Example:
[skyuk_28.2.channels.zip](https://github.com/LraiZer/RadiotimesXmltvEmulator/files/7835573/skyuk_28.2.channels.zip)

**Comment by AbuBaniaz** [comment]
I just tried it and it worked fine for me for 13e. Maybe a glitch on the satellite at the time?
[radiotimes_13e.zip](https://github.com/LraiZer/RadiotimesXmltvEmulator/files/7835984/radiotimes_13e.zip)

**Comment by LraiZer** [comment]
Those 13e look fine to me too, possibly only a temporary glitch then 👍

**Comment by doglover3920** [comment]
Indeed.
It is OK this morning.
Sorry for bothering.

```
<!-- skyit_13.0 --><channel id="130_64511_433">1:0:1:599:19C8:FBFF:820000:0:0:0:</channel><!-- "Class CNBC" -->
<!-- skyit_13.0 --><channel id="130_64511_108">1:0:1:1FAC:19C8:FBFF:820000:0:0:0:</channel><!-- "Sky News" -->
<!-- skyit_13.0 --><channel id="130_64511_199">1:0:83:2BBF:19C8:FBFF:820000:0:0:0:</channel><!-- "IEPG Data" -->
<!-- skyit_13.0 --><channel id="130_64511_211">1:0:1:2BCB:19C8:FBFF:820000:0:0:0:</channel><!-- "CNN Intl." -->
<!-- skyit_13.0 --><channel id="130_64511_799">1:0:83:2E17:1A2C:FBFF:820000:0:0:0:</channel><!-- "IEPG Data" -->
<!-- skyit_13.0 --><channel id="130_64511_598">1:0:83:E0E:1AF4:FBFF:820000:0:0:0:</channel><!-- "IEPG Data" -->
<!-- skyit_13.0 --><channel id="130_64511_57">1:0:1:FD9:1AF4:FBFF:820000:0:0:0:</channel><!-- "History +1" -->
<!-- skyit_13.0 --><channel id="130_64511_58">1:0:1:FDA:1AF4:FBFF:820000:0:0:0:</channel><!-- "NationalGeo +1" -->
<!-- skyit_13.0 --><channel id="130_64511_322">1:0:1:2C3A:1AF4:FBFF:820000:0:0:0:</channel><!-- "Discovery +1" -->
<!-- skyit_13.0 --><channel id="130_64511_348">1:0:1:3424:1AF4:FBFF:820000:0:0:0:</channel><!-- "NatGeo Wild + 1" -->

```
